spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:oracle:thin:@localhost:1521
    username: kisspa
    password: kisspa
---
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
