spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/sqlite3/test.db
---
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true

